version: 0.2

env:
  variables:
    LANG: "ja_JP.UTF-8"
    LANGUAGE: "ja_JP:ja"

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - yum update -y
      - amazon-linux-extras install docker
      - service docker start
      - curl -L "https://github.com/docker/compose/releases/download/2.28.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        - chmod +x /usr/local/bin/docker-compose

  pre_build:
    commands:
      - echo "Set Locale"
      - export LANG="ja_JP.UTF-8"
      - export LANGUAGE="ja_JP:ja"
      - export LC_ALL="ja_JP.UTF-8"
      - yum list | grep docker
      - docker-compose --version

  build:
    commands:
      - echo Build started on `date`
      - docker-compose up -d
      - docker ps


