version: 0.2

env:
  variables:
    LANG: "ja_JP.UTF-8"
    LANGUAGE: "ja_JP:ja"

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - yum update -y

  pre_build:
    commands:
      - echo "Set Locale"
      - localedef -f UTF-8 -i ja_JP ja_JP.UTF-8
      - export LANG="ja_JP.UTF-8"
      - export LANGUAGE="ja_JP:ja"
      - export LC_ALL="ja_JP.UTF-8"

  build:
    commands:
      - echo Build started on `date`
      - docker-compose up -d
      - docker ps


