AWSTemplateFormatVersion: '2010-09-09'
Description: CodePipeline with CodeBuild for 3 GitHub Repositories using CodeStar Connections

Parameters:
  CodeStarConnectionArn:
    Type: String
    Default: arn:aws:codestar-connections:ap-northeast-1:230467396533:connection/edf2d6e7-60c6-47d5-ac77-68f3a71de8ac
  RepositoryName:
    Type: String
    Default: ykdevs/codebuild-docker
  BranchName:
    Type: String
    Default: main

Resources:
  PipelineArtifactBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub 'codebuild-docker-artifacts-${AWS::AccountId}'
    DeletionPolicy: Delete

  CodePipelineRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub '${AWS::StackName}-CodePipelineRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'codepipeline.amazonaws.com'
            Action: 'sts:AssumeRole'
      Path: '/'
      Policies:
        - PolicyName: !Sub '${AWS::StackName}-CodePipelinePolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 's3:GetObject'
                  - 's3:PutObject'
                  - 's3:ListBucket'
                  - 'codecommit:GetRepository'
                  - 'codestar-connections:UseConnection'
                  - 'codebuild:StartBuild'
                  - 'codebuild:BatchGetBuilds'
                Resource: '*'

  CodeBuildRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub '${AWS::StackName}-CodeBuildRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'codebuild.amazonaws.com'
            Action: 'sts:AssumeRole'
      Path: '/'
      Policies:
        - PolicyName: !Sub '${AWS::StackName}-CodeBuildPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                  - 's3:GetObject'
                  - 's3:PutObject'
                  - 'codecommit:GitPull'
                  - 'codestar-connections:UseConnection'
                  - 'ecr:GetAuthorizationToken'
                  - 'ecr:BatchCheckLayerAvailability'
                  - 'ecr:GetDownloadUrlForLayer'
                  - 'ecr:BatchGetImage'
                  - 'ecr:CompleteLayerUpload'
                  - 'ecr:InitiateLayerUpload'
                  - 'ecr:PutImage'
                  - 'ecr:UploadLayerPart'
                Resource: '*'

  CodeBuildProject:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      Name: !Sub '${AWS::StackName}-CodeBuildProject'
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Environment:
        ComputeType: 'BUILD_GENERAL1_SMALL'
        Image: 'aws/codebuild/amazonlinux2-x86_64-standard:4.0'
        PrivilegedMode: true
        Type: 'LINUX_CONTAINER'
      Source:
        Type: 'CODEPIPELINE'
      Artifacts:
        Type: 'CODEPIPELINE'
      TimeoutInMinutes: 60

  CodePipeline:
    Type: 'AWS::CodePipeline::Pipeline'
    Properties:
      RoleArn: !GetAtt CodePipelineRole.Arn
      ArtifactStore:
        Type: 'S3'
        Location: !Ref PipelineArtifactBucket
      PipelineType: V2
      Stages:
        - Name: 'Source'
          Actions:
            - Name: 'Source'
              ActionTypeId:
                Category: 'Source'
                Owner: 'AWS'
                Provider: 'CodeStarSourceConnection'
                Version: '1'
              OutputArtifacts:
                - Name: 'Source'
              Configuration:
                ConnectionArn: !Ref CodeStarConnectionArn
                FullRepositoryId: !Ref RepositoryName
                BranchName: !Ref BranchName
                OutputArtifactFormat: 'CODEBUILD_CLONE_REF'
              RunOrder: 1
        - Name: 'Build'
          Actions:
            - Name: 'BuildAction'
              ActionTypeId:
                Category: 'Build'
                Owner: 'AWS'
                Provider: 'CodeBuild'
                Version: '1'
              InputArtifacts:
                - Name: 'Source'
              Configuration:
                ProjectName: !Ref CodeBuildProject
                PrimarySource: 'Source'
              RunOrder: 1

